/**
 * Investigation Engine
 * 
 * Executes investigation plans generated by AI.
 * Coordinates across multiple MCP tools (GitHub, Logs, Prometheus).
 */

import { getMCPClient } from '../mcp/client.js';
import { InvestigationPlan, MergedContext } from '../ai/provider.js';
import { investigationLogger } from '../config/logger.js';

export interface InvestigationResult {
  tool: string;
  action: string;
  query: string;
  purpose: string;
  success: boolean;
  data?: any;
  error?: string;
  summary: string;
}

export interface InvestigationSummary {
  results: InvestigationResult[];
  overallStatus: 'success' | 'partial' | 'failed';
  keyFindings: string[];
  recommendations: string[];
}

/**
 * Execute an investigation plan
 */
export async function executeInvestigation(
  plan: InvestigationPlan,
  context: MergedContext
): Promise<InvestigationSummary> {
  investigationLogger.info('[Investigation] Starting investigation...');
  investigationLogger.debug('[Investigation] Plan:', plan);

  const results: InvestigationResult[] = [];
  const keyFindings: string[] = [];
  const recommendations: string[] = [];

  const client = getMCPClient();

  for (const step of plan.steps) {
    investigationLogger.info(`[Investigation] Executing step: ${step.tool}/${step.action}`);

    try {
      const result = await executeStep(client, step, context);
      results.push(result);

      if (result.success) {
        keyFindings.push(`[${step.tool}] ${result.summary}`);
      } else {
        recommendations.push(`Failed to query ${step.tool}: ${result.error}`);
      }
    } catch (error: any) {
      investigationLogger.error(`[Investigation] Step failed: ${step.tool}/${step.action}`, error);
      results.push({
        tool: step.tool,
        action: step.action,
        query: step.query,
        purpose: step.purpose,
        success: false,
        error: error.message,
        summary: `Failed: ${error.message}`,
      });
    }
  }

  // Determine overall status
  const successCount = results.filter((r) => r.success).length;
  const overallStatus: InvestigationSummary['overallStatus'] =
    successCount === results.length
      ? 'success'
      : successCount > 0
      ? 'partial'
      : 'failed';

  investigationLogger.info(
    `[Investigation] Complete: ${successCount}/${results.length} steps succeeded`
  );

  return {
    results,
    overallStatus,
    keyFindings,
    recommendations,
  };
}

/**
 * Execute a single investigation step
 */
async function executeStep(
  client: any,
  step: InvestigationPlan['steps'][0],
  context: MergedContext
): Promise<InvestigationResult> {
  const { tool, action, query, purpose } = step;

  let result: any;
  let summary = '';

  switch (tool) {
    case 'github':
      result = await executeGitHubStep(client, action, query, context);
      summary = summarizeGitHubResult(result, action);
      break;

    case 'logs':
      result = await executeLogsStep(client, action, query, context);
      summary = summarizeLogsResult(result, action);
      break;

    case 'prometheus':
      result = await executePrometheusStep(client, action, query, context);
      summary = summarizePrometheusResult(result, action);
      break;

    default:
      throw new Error(`Unknown investigation tool: ${tool}`);
  }

  return {
    tool,
    action,
    query,
    purpose,
    success: true,
    data: result,
    summary,
  };
}

/**
 * GitHub investigation steps
 */
async function executeGitHubStep(
  client: any,
  action: string,
  query: string,
  context: MergedContext
): Promise<any> {
  // Parse query for owner/repo
  const parts = query.split('/');
  const owner = parts[0] || 'owner';
  const repo = parts[1] || 'repo';

  switch (action) {
    case 'get_recent_commits':
      return await client.callTool('github', 'github_get_recent_commits', {
        owner,
        repo,
        per_page: 10,
      });

    case 'get_recent_prs':
      return await client.callTool('github', 'github_get_recent_prs', {
        owner,
        repo,
        per_page: 10,
      });

    case 'search_issues':
      return await client.callTool('github', 'github_search_issues', {
        q: query,
        per_page: 10,
      });

    default:
      throw new Error(`Unknown GitHub action: ${action}`);
  }
}

/**
 * Logs investigation steps
 */
async function executeLogsStep(
  client: any,
  action: string,
  query: string,
  context: MergedContext
): Promise<any> {
  // Placeholder for logs integration
  // In production, implement actual logs MCP server
  return {
    action,
    query,
    message: 'Logs MCP server not yet implemented',
    entries: [],
  };
}

/**
 * Prometheus investigation steps
 */
async function executePrometheusStep(
  client: any,
  action: string,
  query: string,
  context: MergedContext
): Promise<any> {
  switch (action) {
    case 'check_health':
      return await client.callTool('prometheus', 'prometheus_check_service_health', {
        service: query,
        lookback: '5m',
      });

    case 'query':
      return await client.callTool('prometheus', 'prometheus_query', {
        query,
      });

    case 'get_alerts':
      return await client.callTool('prometheus', 'prometheus_get_alerts', {
        filter: query,
      });

    default:
      throw new Error(`Unknown Prometheus action: ${action}`);
  }
}

/**
 * Summarize GitHub results
 */
function summarizeGitHubResult(result: any, action: string): string {
  try {
    const data = JSON.parse(result.content[0].text);

    if (action === 'get_recent_commits') {
      return `Found ${data.length || 0} recent commits. Latest: ${data[0]?.message?.substring(0, 50) || 'N/A'}`;
    }

    if (action === 'get_recent_prs') {
      return `Found ${data.length || 0} recent PRs. Latest: ${data[0]?.title || 'N/A'}`;
    }

    if (action === 'search_issues') {
      return `Found ${data.total_count || 0} matching issues`;
    }

    return 'GitHub query completed';
  } catch {
    return 'GitHub query completed';
  }
}

/**
 * Summarize logs results
 */
function summarizeLogsResult(result: any, action: string): string {
  return `Logs query completed: ${action}`;
}

/**
 * Summarize Prometheus results
 */
function summarizePrometheusResult(result: any, action: string): string {
  try {
    const data = JSON.parse(result.content[0].text);

    if (action === 'check_health') {
      return `Service ${data.service}: ${data.status} (up: ${data.isUp}, error rate: ${data.errorRate})`;
    }

    if (action === 'query') {
      const value = data.data?.result?.[0]?.value?.[1];
      return `Query result: ${value || 'no data'}`;
    }

    if (action === 'get_alerts') {
      return `Found ${data.total || 0} active alerts`;
    }

    return 'Prometheus query completed';
  } catch {
    return 'Prometheus query completed';
  }
}

/**
 * Format investigation summary for AI
 */
export function formatInvestigationSummary(
  summary: InvestigationSummary
): string {
  const lines: string[] = [
    '## Investigation Summary',
    `Status: ${summary.overallStatus.toUpperCase()}`,
    '',
    '### Key Findings',
  ];

  if (summary.keyFindings.length === 0) {
    lines.push('- No findings');
  } else {
    for (const finding of summary.keyFindings) {
      lines.push(`- ${finding}`);
    }
  }

  if (summary.recommendations.length > 0) {
    lines.push('', '### Recommendations');
    for (const rec of summary.recommendations) {
      lines.push(`- ${rec}`);
    }
  }

  return lines.join('\n');
}
